2021-04-10 09:48:49,193:DEBUG:certbot._internal.main:certbot version: 1.14.0
2021-04-10 09:48:49,194:DEBUG:certbot._internal.main:Location of certbot entry point: /usr/local/Cellar/certbot/1.14.0/libexec/bin/certbot
2021-04-10 09:48:49,194:DEBUG:certbot._internal.main:Arguments: ['--config-dir', '/Users/honguuikuto/Desktop/PythonProject/django-api-project2/certbot', '--work-dir', '/Users/honguuikuto/Desktop/PythonProject/django-api-project2/certbot', '--logs-dir', '/Users/honguuikuto/Desktop/PythonProject/django-api-project2/certbot', '--manual', '--preferred-challenges', 'dns']
2021-04-10 09:48:49,194:DEBUG:certbot._internal.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#apache,PluginEntryPoint#manual,PluginEntryPoint#nginx,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2021-04-10 09:48:49,219:DEBUG:certbot._internal.log:Root logging level set at 20
2021-04-10 09:48:49,219:INFO:certbot._internal.log:Saving debug log to /Users/honguuikuto/Desktop/PythonProject/django-api-project2/certbot/letsencrypt.log
2021-04-10 09:48:49,219:DEBUG:certbot._internal.plugins.selection:Requested authenticator manual and installer None
2021-04-10 09:48:49,222:DEBUG:certbot._internal.plugins.selection:Single candidate plugin: * manual
Description: Manual configuration or run your own shell scripts
Interfaces: IAuthenticator, IPlugin
Entry point: manual = certbot._internal.plugins.manual:Authenticator
Initialized: <certbot._internal.plugins.manual.Authenticator object at 0x10bccb9a0>
Prep: True
2021-04-10 09:48:49,222:DEBUG:certbot._internal.plugins.selection:Selected authenticator <certbot._internal.plugins.manual.Authenticator object at 0x10bccb9a0> and installer None
2021-04-10 09:48:49,222:INFO:certbot._internal.plugins.selection:Plugins selected: Authenticator manual, Installer None
2021-04-10 09:49:03,114:DEBUG:acme.client:Sending GET request to https://acme-v02.api.letsencrypt.org/directory.
2021-04-10 09:49:03,159:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): acme-v02.api.letsencrypt.org:443
2021-04-10 09:49:03,807:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "GET /directory HTTP/1.1" 200 658
2021-04-10 09:49:03,809:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Sat, 10 Apr 2021 00:49:04 GMT
Content-Type: application/json
Content-Length: 658
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "4cOxrwYY-h0": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417",
  "keyChange": "https://acme-v02.api.letsencrypt.org/acme/key-change",
  "meta": {
    "caaIdentities": [
      "letsencrypt.org"
    ],
    "termsOfService": "https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf",
    "website": "https://letsencrypt.org"
  },
  "newAccount": "https://acme-v02.api.letsencrypt.org/acme/new-acct",
  "newNonce": "https://acme-v02.api.letsencrypt.org/acme/new-nonce",
  "newOrder": "https://acme-v02.api.letsencrypt.org/acme/new-order",
  "revokeCert": "https://acme-v02.api.letsencrypt.org/acme/revoke-cert"
}
2021-04-10 09:49:05,297:DEBUG:acme.client:Requesting fresh nonce
2021-04-10 09:49:05,297:DEBUG:acme.client:Sending HEAD request to https://acme-v02.api.letsencrypt.org/acme/new-nonce.
2021-04-10 09:49:05,457:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "HEAD /acme/new-nonce HTTP/1.1" 200 0
2021-04-10 09:49:05,457:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Sat, 10 Apr 2021 00:49:05 GMT
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 0104J128PZppBsL_C76DY86iFAPdg1A2pS49veT6HxhseYQ
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800


2021-04-10 09:49:05,457:DEBUG:acme.client:Storing nonce: 0104J128PZppBsL_C76DY86iFAPdg1A2pS49veT6HxhseYQ
2021-04-10 09:49:05,458:DEBUG:acme.client:JWS payload:
b'{\n  "contact": [\n    "mailto:ikuto.hongu@gmail.com"\n  ],\n  "termsOfServiceAgreed": true\n}'
2021-04-10 09:49:05,460:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/new-acct:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAiandrIjogeyJuIjogIjNnVm9FZHhTUmY1WWRYQndPUTBJMnRmVTA0Mk40QUs5LVpISXlvanlmbW41WkFJWDhpQW9lRlVlcXl3Q1UxU3FfLVRPdmRWNFNEeU56VjB2MFJoSVp6Q3JvYVVaRjlWbEFEMFJlZWhMS0VlYmtIUTJnQVRTLWJkd2NpRE5uQnlMRjhqQVN1S0VXRXpQdE9JRVM0Zkg5UWdCWlBkczVVR1E4NkNVNGROeW9sczIxdmFaQW5iblY5eGZ6eEVVZmp3SWxQN3M2S0Nkemh3bjhWRFV0YVptYTdvRS1Kd182dHhjZ2lMUFpMbmFBYk1DN3N2dGdzem9scWpfUlN0MWhiSjdkOHJKN2x1ZGZRdjlxLV90dVE5TkZ1aWpwWEpvM1pmaE1BeHc4REt0VHZ2NEFmZDJ4Q0xPUXJPYy1mdkU1eTctd0RfU1hxeWlxZi15aE9xMkNxNFRvdyIsICJlIjogIkFRQUIiLCAia3R5IjogIlJTQSJ9LCAibm9uY2UiOiAiMDEwNEoxMjhQWnBwQnNMX0M3NkRZODZpRkFQZGcxQTJwUzQ5dmVUNkh4aHNlWVEiLCAidXJsIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL25ldy1hY2N0In0",
  "signature": "QhyIuQTC0mUbpSmKXnKqBR9qH3EfydrxAyyX07x8-hbcel0KpfIc6gXNSvGm1QvVq-gu5y_O7Fuw4LRenUru6o9mRDyvk-fMuxUl1D-uLPvsQG_9xORqoP7BB79kaddugkNpEDEOsQ5HnYHlse3ZZ-Ke4Xc_2_3mC8ymVLylXcmkZKAqSjeEUnrHq-qwKyU-MNtveuNrB_9nFidkZq3j5l0IQXm0Vj-R0zlHbQreg98_Ge6z51STfPK-VLwNb9oAMpRCjPOLuGnc3Pj0qN74pZhkiHxWz80LawWTtc9R-NC4mk2KI0blu7W-xr1tkfH3ERBN4DmIDVNuQ5Biowa4tg",
  "payload": "ewogICJjb250YWN0IjogWwogICAgIm1haWx0bzppa3V0by5ob25ndUBnbWFpbC5jb20iCiAgXSwKICAidGVybXNPZlNlcnZpY2VBZ3JlZWQiOiB0cnVlCn0"
}
2021-04-10 09:49:05,701:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/new-acct HTTP/1.1" 201 565
2021-04-10 09:49:05,702:DEBUG:acme.client:Received response:
HTTP 201
Server: nginx
Date: Sat, 10 Apr 2021 00:49:05 GMT
Content-Type: application/json
Content-Length: 565
Connection: keep-alive
Boulder-Requester: 118659046
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index", <https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf>;rel="terms-of-service"
Location: https://acme-v02.api.letsencrypt.org/acme/acct/118659046
Replay-Nonce: 0104-vk3tN9UFWrBuxEg4r0BDKF1fNvcywFgE62hDQVtTvY
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "key": {
    "kty": "RSA",
    "n": "3gVoEdxSRf5YdXBwOQ0I2tfU042N4AK9-ZHIyojyfmn5ZAIX8iAoeFUeqywCU1Sq_-TOvdV4SDyNzV0v0RhIZzCroaUZF9VlAD0ReehLKEebkHQ2gATS-bdwciDNnByLF8jASuKEWEzPtOIES4fH9QgBZPds5UGQ86CU4dNyols21vaZAnbnV9xfzxEUfjwIlP7s6KCdzhwn8VDUtaZma7oE-Jw_6txcgiLPZLnaAbMC7svtgszolqj_RSt1hbJ7d8rJ7ludfQv9q-_tuQ9NFuijpXJo3ZfhMAxw8DKtTvv4Afd2xCLOQrOc-fvE5y7-wD_SXqyiqf-yhOq2Cq4Tow",
    "e": "AQAB"
  },
  "contact": [
    "mailto:ikuto.hongu@gmail.com"
  ],
  "initialIp": "219.164.164.178",
  "createdAt": "2021-04-10T00:49:05.91958176Z",
  "status": "valid"
}
2021-04-10 09:49:05,703:DEBUG:acme.client:Storing nonce: 0104-vk3tN9UFWrBuxEg4r0BDKF1fNvcywFgE62hDQVtTvY
2021-04-10 09:49:07,556:DEBUG:certbot.display.util:Notifying user: Account registered.
2021-04-10 09:49:07,556:DEBUG:certbot._internal.main:Picked account: <Account(RegistrationResource(body=Registration(key=JWKRSA(key=<ComparableRSAKey(<cryptography.hazmat.backends.openssl.rsa._RSAPublicKey object at 0x10bd1bdf0>)>), contact=('mailto:ikuto.hongu@gmail.com',), agreement=None, status='valid', terms_of_service_agreed=None, only_return_existing=None, external_account_binding=None), uri='https://acme-v02.api.letsencrypt.org/acme/acct/118659046', new_authzr_uri=None, terms_of_service='https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf'), f3a0886d4c5cde79e291857d1605c31f, Meta(creation_dt=datetime.datetime(2021, 4, 10, 0, 49, 5, tzinfo=<UTC>), creation_host='1.0.0.127.in-addr.arpa', register_to_eff=None))>
2021-04-10 09:49:07,556:DEBUG:certbot.display.ops:No installer, picking names manually
2021-04-10 09:49:27,697:DEBUG:certbot.display.util:Notifying user: Requesting a certificate for apps.quouze.com
2021-04-10 09:49:27,739:DEBUG:certbot.crypto_util:Generating RSA key (2048 bits): /Users/honguuikuto/Desktop/PythonProject/django-api-project2/certbot/keys/0000_key-certbot.pem
2021-04-10 09:49:27,745:DEBUG:certbot.crypto_util:Creating CSR: /Users/honguuikuto/Desktop/PythonProject/django-api-project2/certbot/csr/0000_csr-certbot.pem
2021-04-10 09:49:27,745:DEBUG:acme.client:JWS payload:
b'{\n  "identifiers": [\n    {\n      "type": "dns",\n      "value": "apps.quouze.com"\n    }\n  ]\n}'
2021-04-10 09:49:27,748:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/new-order:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMTE4NjU5MDQ2IiwgIm5vbmNlIjogIjAxMDQtdmszdE45VUZXckJ1eEVnNHIwQkRLRjFmTnZjeXdGZ0U2MmhEUVZ0VHZZIiwgInVybCI6ICJodHRwczovL2FjbWUtdjAyLmFwaS5sZXRzZW5jcnlwdC5vcmcvYWNtZS9uZXctb3JkZXIifQ",
  "signature": "NkLBCX10q3A-2r-Umnd_8_3W5-5kz0ZhqacJaHmjlDdI2GD0E_qDLvYHB5CQbsK3kBcpbyK0JGUOdyJ_GOX7u16zMYywoS_QcVNRnIgCdKPCQHczw0NuCDNxOXE3sr7fGTJtjidN6M7LFM4oiUyBPO8xF74IiRI2ZicUHHBvAe5m2GLXNTjzDKR8vAT0oeC00C5Ch15NbiriseBfrVu2bwJwlDI5x147w83YX49Xm9dAuab2XCXKtS3a8s-U3x5z6VFkPfku2i5Uht9yXPJvcN17EjOpzknGChLsxjUbXJBzOK9QTFe7qzhCtSvhBqr31zIG93z9B1m-eR-K0qLaPw",
  "payload": "ewogICJpZGVudGlmaWVycyI6IFsKICAgIHsKICAgICAgInR5cGUiOiAiZG5zIiwKICAgICAgInZhbHVlIjogImFwcHMucXVvdXplLmNvbSIKICAgIH0KICBdCn0"
}
2021-04-10 09:49:28,145:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/new-order HTTP/1.1" 201 337
2021-04-10 09:49:28,147:DEBUG:acme.client:Received response:
HTTP 201
Server: nginx
Date: Sat, 10 Apr 2021 00:49:28 GMT
Content-Type: application/json
Content-Length: 337
Connection: keep-alive
Boulder-Requester: 118659046
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Location: https://acme-v02.api.letsencrypt.org/acme/order/118659046/8970244326
Replay-Nonce: 0103UIZOaVZucSUkVz4LrAa9c8Zfvn0wQ25LQpij8KvPPmk
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "status": "pending",
  "expires": "2021-04-17T00:49:28Z",
  "identifiers": [
    {
      "type": "dns",
      "value": "apps.quouze.com"
    }
  ],
  "authorizations": [
    "https://acme-v02.api.letsencrypt.org/acme/authz-v3/12216871470"
  ],
  "finalize": "https://acme-v02.api.letsencrypt.org/acme/finalize/118659046/8970244326"
}
2021-04-10 09:49:28,147:DEBUG:acme.client:Storing nonce: 0103UIZOaVZucSUkVz4LrAa9c8Zfvn0wQ25LQpij8KvPPmk
2021-04-10 09:49:28,150:DEBUG:acme.client:JWS payload:
b''
2021-04-10 09:49:28,154:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/authz-v3/12216871470:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMTE4NjU5MDQ2IiwgIm5vbmNlIjogIjAxMDNVSVpPYVZadWNTVWtWejRMckFhOWM4WmZ2bjB3UTI1TFFwaWo4S3ZQUG1rIiwgInVybCI6ICJodHRwczovL2FjbWUtdjAyLmFwaS5sZXRzZW5jcnlwdC5vcmcvYWNtZS9hdXRoei12My8xMjIxNjg3MTQ3MCJ9",
  "signature": "LlPHfLIuGtI4Drh4TGqzap3sLiLp4DkV30NFwFvip6erBsDYuWaKBP4z4PnhAJwvb1KIqmxFL6Pg-YPQ2K1uw8q6DVC-QA-kM3Q-3-eaSxV8rP0pEEWqcRa6kRFepXZYZj6YCQ7i4gJeLMqgoTKWo5x_t9mV6KPux00jWeIMhVkHDmhL020bKNzGEIe4eT1yyNHBVbr2zg-YkvsYvF1GJYl-MFWG54sBu-IH7yf8B7W5hwCK8jGDC0LrMQaLOBiwoxWe_uTlbXh0gZXnkNc96Mzfm96CLVlxGoxYOpOUikO4lRqb-OpUbAsjfHkv106SJzBqes5tAJMFR3Kd2kBCTw",
  "payload": ""
}
2021-04-10 09:49:28,346:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/authz-v3/12216871470 HTTP/1.1" 200 796
2021-04-10 09:49:28,347:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Sat, 10 Apr 2021 00:49:28 GMT
Content-Type: application/json
Content-Length: 796
Connection: keep-alive
Boulder-Requester: 118659046
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 01044nebLLM0hcsYBUHlh2pyBlMEtyknePAUAgANJY2MqJ0
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "identifier": {
    "type": "dns",
    "value": "apps.quouze.com"
  },
  "status": "pending",
  "expires": "2021-04-17T00:49:28Z",
  "challenges": [
    {
      "type": "http-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/12216871470/dQDnhw",
      "token": "HrkClfRpMxTXmETNkdMql2XoxIkgx1a86hsv-94I3qM"
    },
    {
      "type": "dns-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/12216871470/NCRPJw",
      "token": "HrkClfRpMxTXmETNkdMql2XoxIkgx1a86hsv-94I3qM"
    },
    {
      "type": "tls-alpn-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/12216871470/4C6h4g",
      "token": "HrkClfRpMxTXmETNkdMql2XoxIkgx1a86hsv-94I3qM"
    }
  ]
}
2021-04-10 09:49:28,347:DEBUG:acme.client:Storing nonce: 01044nebLLM0hcsYBUHlh2pyBlMEtyknePAUAgANJY2MqJ0
2021-04-10 09:49:28,348:INFO:certbot._internal.auth_handler:Performing the following challenges:
2021-04-10 09:49:28,348:INFO:certbot._internal.auth_handler:dns-01 challenge for apps.quouze.com
2021-04-10 09:49:28,349:DEBUG:certbot.display.util:Notifying user: Please deploy a DNS TXT record under the name
_acme-challenge.apps.quouze.com with the following value:

htXQ_g8_UM0KPC4sZQGGmCR2OkchnW970rd6uiMUcHA

Before continuing, verify the record is deployed.
2021-04-10 09:51:36,993:INFO:certbot._internal.auth_handler:Waiting for verification...
2021-04-10 09:51:36,998:DEBUG:acme.client:JWS payload:
b'{}'
2021-04-10 09:51:37,003:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/chall-v3/12216871470/NCRPJw:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMTE4NjU5MDQ2IiwgIm5vbmNlIjogIjAxMDQ0bmViTExNMGhjc1lCVUhsaDJweUJsTUV0eWtuZVBBVUFnQU5KWTJNcUowIiwgInVybCI6ICJodHRwczovL2FjbWUtdjAyLmFwaS5sZXRzZW5jcnlwdC5vcmcvYWNtZS9jaGFsbC12My8xMjIxNjg3MTQ3MC9OQ1JQSncifQ",
  "signature": "mGRvG3gjzpeg7y8FV9RDqGW118l-asPE8ygjEFc0qOG3GXZpy2Uo6V8t1pMjNFBhzNGzLOH6-cOfl9Y0h4kUufC48eUY7Ojbp-u3Y9_TVYnHC5ATNZU1RgDqRAYCE3pTO2B_j96LfGy7oc8YPaGL4pJ2-MSi7BWJM11x4RZjcwt0hQadpoXSFIgASQWIVNONCucqBFTi7ivYaqzkjv7IM5sE_pxcrJwjVD-V0yZWlJsHxuC4PT25viovBaUdX1kUmg8NCfHZMtz0vW4AqBpiq3kBHQqDzH6GGPXjFoKe2Pgr0gbZeRvwIQ4k7_EHKQPpn2SIOQwGva9D_MIV2eZjyA",
  "payload": "e30"
}
2021-04-10 09:51:37,254:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/chall-v3/12216871470/NCRPJw HTTP/1.1" 200 185
2021-04-10 09:51:37,256:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Sat, 10 Apr 2021 00:51:37 GMT
Content-Type: application/json
Content-Length: 185
Connection: keep-alive
Boulder-Requester: 118659046
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index", <https://acme-v02.api.letsencrypt.org/acme/authz-v3/12216871470>;rel="up"
Location: https://acme-v02.api.letsencrypt.org/acme/chall-v3/12216871470/NCRPJw
Replay-Nonce: 0104c2pjiJqRJHyZrf4lajsCq3QzRRu01AHueEvv6R8uSVE
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "type": "dns-01",
  "status": "pending",
  "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/12216871470/NCRPJw",
  "token": "HrkClfRpMxTXmETNkdMql2XoxIkgx1a86hsv-94I3qM"
}
2021-04-10 09:51:37,256:DEBUG:acme.client:Storing nonce: 0104c2pjiJqRJHyZrf4lajsCq3QzRRu01AHueEvv6R8uSVE
2021-04-10 09:51:38,264:DEBUG:acme.client:JWS payload:
b''
2021-04-10 09:51:38,270:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/authz-v3/12216871470:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMTE4NjU5MDQ2IiwgIm5vbmNlIjogIjAxMDRjMnBqaUpxUkpIeVpyZjRsYWpzQ3EzUXpSUnUwMUFIdWVFdnY2Ujh1U1ZFIiwgInVybCI6ICJodHRwczovL2FjbWUtdjAyLmFwaS5sZXRzZW5jcnlwdC5vcmcvYWNtZS9hdXRoei12My8xMjIxNjg3MTQ3MCJ9",
  "signature": "0em0cwHrgHxvwHIN4LoCUcuRlQQ3Ps8rVRCEEwIjTZpWWVsbo6qUCOu9pD5Gm5xUwG2Vwba_TfcEizkoUAIYZEHGje_qvVQ1cH7s-tWw4MeNJpgMb5R_bUY-MBdM_yZtc2VKXdWs5mMXqrVnpUnTlOXqWbPvmHm6KJZ4ngDoBrClvZA6JX-DqyVVHfyGplqA1hlFbCLHNhSOBXFUSZL_MreVrhyzG9a-5tgpKcl44ipR6yrhItFm7egN8-PPVrMYrYbbZjCd4Wwxv56AJy2KooVNk3cPzewiv11oml7BteV8Pbdwe0JKAoZNG4maihW03UG0LOSsoa87vQ0QO4L7ug",
  "payload": ""
}
2021-04-10 09:51:38,474:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/authz-v3/12216871470 HTTP/1.1" 200 594
2021-04-10 09:51:38,476:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Sat, 10 Apr 2021 00:51:38 GMT
Content-Type: application/json
Content-Length: 594
Connection: keep-alive
Boulder-Requester: 118659046
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 0104bebv63RsU6qwm2J5gl8zIa5e8rTZDb6f47hmNQw25qM
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "identifier": {
    "type": "dns",
    "value": "apps.quouze.com"
  },
  "status": "invalid",
  "expires": "2021-04-17T00:49:28Z",
  "challenges": [
    {
      "type": "dns-01",
      "status": "invalid",
      "error": {
        "type": "urn:ietf:params:acme:error:unauthorized",
        "detail": "No TXT record found at _acme-challenge.apps.quouze.com",
        "status": 403
      },
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/12216871470/NCRPJw",
      "token": "HrkClfRpMxTXmETNkdMql2XoxIkgx1a86hsv-94I3qM",
      "validated": "2021-04-10T00:51:37Z"
    }
  ]
}
2021-04-10 09:51:38,477:DEBUG:acme.client:Storing nonce: 0104bebv63RsU6qwm2J5gl8zIa5e8rTZDb6f47hmNQw25qM
2021-04-10 09:51:38,481:WARNING:certbot._internal.auth_handler:Challenge failed for domain apps.quouze.com
2021-04-10 09:51:38,482:INFO:certbot._internal.auth_handler:dns-01 challenge for apps.quouze.com
2021-04-10 09:51:38,483:DEBUG:certbot._internal.reporter:Reporting to user: The following errors were reported by the server:

Domain: apps.quouze.com
Type:   unauthorized
Detail: No TXT record found at _acme-challenge.apps.quouze.com

To fix these errors, please make sure that your domain name was entered correctly and the DNS A/AAAA record(s) for that domain contain(s) the right IP address.
2021-04-10 09:51:38,486:DEBUG:certbot._internal.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/usr/local/Cellar/certbot/1.14.0/libexec/lib/python3.9/site-packages/certbot/_internal/auth_handler.py", line 91, in handle_authorizations
    self._poll_authorizations(authzrs, max_retries, best_effort)
  File "/usr/local/Cellar/certbot/1.14.0/libexec/lib/python3.9/site-packages/certbot/_internal/auth_handler.py", line 179, in _poll_authorizations
    raise errors.AuthorizationError('Some challenges have failed.')
certbot.errors.AuthorizationError: Some challenges have failed.

2021-04-10 09:51:38,486:DEBUG:certbot._internal.error_handler:Calling registered functions
2021-04-10 09:51:38,486:INFO:certbot._internal.auth_handler:Cleaning up challenges
2021-04-10 09:51:38,488:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/local/Cellar/certbot/1.14.0/libexec/bin/certbot", line 33, in <module>
    sys.exit(load_entry_point('certbot==1.14.0', 'console_scripts', 'certbot')())
  File "/usr/local/Cellar/certbot/1.14.0/libexec/lib/python3.9/site-packages/certbot/main.py", line 15, in main
    return internal_main.main(cli_args)
  File "/usr/local/Cellar/certbot/1.14.0/libexec/lib/python3.9/site-packages/certbot/_internal/main.py", line 1435, in main
    return config.func(config, plugins)
  File "/usr/local/Cellar/certbot/1.14.0/libexec/lib/python3.9/site-packages/certbot/_internal/main.py", line 1304, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
  File "/usr/local/Cellar/certbot/1.14.0/libexec/lib/python3.9/site-packages/certbot/_internal/main.py", line 140, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
  File "/usr/local/Cellar/certbot/1.14.0/libexec/lib/python3.9/site-packages/certbot/_internal/client.py", line 444, in obtain_and_enroll_certificate
    cert, chain, key, _ = self.obtain_certificate(domains)
  File "/usr/local/Cellar/certbot/1.14.0/libexec/lib/python3.9/site-packages/certbot/_internal/client.py", line 374, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
  File "/usr/local/Cellar/certbot/1.14.0/libexec/lib/python3.9/site-packages/certbot/_internal/client.py", line 424, in _get_order_and_authorizations
    authzr = self.auth_handler.handle_authorizations(orderr, best_effort)
  File "/usr/local/Cellar/certbot/1.14.0/libexec/lib/python3.9/site-packages/certbot/_internal/auth_handler.py", line 91, in handle_authorizations
    self._poll_authorizations(authzrs, max_retries, best_effort)
  File "/usr/local/Cellar/certbot/1.14.0/libexec/lib/python3.9/site-packages/certbot/_internal/auth_handler.py", line 179, in _poll_authorizations
    raise errors.AuthorizationError('Some challenges have failed.')
certbot.errors.AuthorizationError: Some challenges have failed.
2021-04-10 09:51:38,492:ERROR:certbot._internal.log:Some challenges have failed.
